language: python

python:
  - "3.6.7"

install:
  - pip install -r requirements.txt

services:
  - postgresql

env:
  - CC_TEST_REPORTER_ID=3c1b93773a26e0d4e5430a8c1b6be8e3784dca4e1e6f7b94e9e6c8b6e5ed777d

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - psql -c 'create database apisendit;' -U postgres
  - psql -c 'create database apitest;' -U postgres

script:
  - pytest --cov-report term-missing --cov=app

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
- coveralls