language: python

python:
  - "3.6.7"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database apisendit;' -U postgres

script:
  - pytest --cov-report term-missing --cov=app

after_success:
- coveralls